### PR TITLE
Spliting ChinookTest.cpp

### PR DESCRIPTION
**Pull request by Patrick-Liao**

### CODE REVIEW

**Comment by thefangbear** [comment]
This change is [Reviewable](https://reviewable.io/reviews/lsrobotics/chinook/12)

**Comment by thefangbear** [comment]
I will merge this only when travis test passes

**Comment by thefangbear** [comment]
Also the commit titles are not acceptable

**Comment by thefangbear** [comment]
I would like the DriveTrain to be separated

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lsrobotics/chinook/12#-:-Kc9sr8WgrnbXt04s6hR:b-xvbmby)*

**Comment by thefangbear** [comment]
Everything else is fine - I'll merge when DriveTrain gets separated

---

Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lsrobotics/chinook/12#-:-Kc9tD-WTirnlzEqWlq4:bor3cgy)*

**Comment by thefangbear** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/ChinookTest.cpp, line 15 at r3](https://reviewable.io:443/reviews/lsrobotics/chinook/12#-Kc9tLkZq4Mh057L-yfb:-Kc9tLkZq4Mh057L-yfc:bhvkh7e) ([raw file](https://github.com/lsrobotics/chinook/blob/c1d68bd04bca2db20fbe7add6247b961636a550b/src/ChinookTest.cpp#L15)):*
> ```cpp
> 
> 
> class DriveTrain {
> ```

Separate drive train

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lsrobotics/chinook/12)*

**Comment by Patrick-Liao** [comment]
Passed. Please merge it.

**Comment by tylerliu** [comment]
Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lsrobotics/chinook/12)*

**Comment by thefangbear** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lsrobotics/chinook/12#-:-KcBM3WkICRhqXId8oEt:bg7igk9)*

**Pull request merged**
